version: "3.9"

services:
  qachallenge:
    image: farlahi00/qachallenge
    container_name: qachallenge-api
    ports:
      - "80:80"
    restart: unless-stopped
    # Volumes comentados para evitar erros no macOS
    # volumes:
    #   - ./data/sql_app.db:/app/sql_app.db
